version: "3.4"
services: 
  api:
    container_name: api
    image: ama/api:1.0.0
    environment:
      NODE_ENV: production
      HOST: "0.0.0.0"
      PORT: 5000
      DB_HOST: db
    build:
      context: ../ama-api
      target: api_debug
    #working_dir: /work      #comment out for build.target:prod
    #entrypoint: /bin/sh     #comment out for build.target:prod
    #stdin_open: true        #comment out for build.target:prod
    #tty: true               #comment out for build.target:prod
    volumes:
    - ../ama-api/src/:/work/src/
    ports:
      - 5002:5000
      - 9229:9229            #debug port
    depends_on: 
      [db]
  db:
    container_name: mongodb
    image: mongo:4.2.5
    ports:
      - "27018:27017"
    volumes:
      - ./.data:/data/db
  web:
    container_name: web
    image: ama/web:1.0.0
    environment:
      NODE_ENV: production
      HOST: "0.0.0.0"
      PORT: 3000
      REACT_APP_API_HOST: "0.0.0.0"
      REACT_APP_API_PORT: 5002
    build:
      context: ../ama-web
      target: web_debug
    stdin_open: true
    volumes:
    - ./web/src/:/app/src/
    - ./web/public/:/app/public/
    working_dir: /app
    ports:
      - 3000:3000
      - 9222:9222    